eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka

zuul:
  prefix: /api
  routes:
     routes:
       path: /routes/**
       serviceId: travel-routeservice
     cities:
       path: /cities/**
       serviceId: travel-cityservice

    

